language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly

os:
  - linux

cache: cargo

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test --verbose

addons:
  apt:
    packages:
      - libfftw3-dev
