[package]
name = "ndarray-fftw"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
ndarray = "0.7"
num-complex = "*"

[dependencies.fftw3-sys]
path = "fftw3-sys"
